name: Continuous Integration

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build and Test Job
    timeout-minutes: 360
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nixpkgs: [ lockfile, nixos-19.09, nixos-unstable ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Install Nix
      uses: cachix/install-nix-action@v6

    - name: nix-build (for ${{ matrix.nixpkgs }})
      run: nix-build --no-link release.nix --arg nixpkgs channel:${{ matrix.nixpkgs }}

    - name: nix-build -A tests
      run: nix-build --no-link release.nix --arg nixpkgs channel:${{ matrix.nixpkgs }} -A test
